#:schema https://raw.githubusercontent.com/insanum/gcalcli/HEAD/data/config-schema.json
[default]
# long-format = %s - %e

[calendars]
# default-calendars = ["Main", "Time-Block", "All Courses - University of Waterloo", "Formula 1", "Ren's Calendar"]
ignore-calendars = ["Ren's Calendar"]
# Main = 28

[output]
week-start = "monday"
